# Generated by Django 5.2 on 2026-02-01 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Enter a valid username', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
